main/urls.py
from django.urls import path
from . import views
from .views import TaskCreateView, TaskListView, TaskDetailView

urlpatterns = [
    path('', views.index, name="home" ),
    path('about-us', views.about, name="about"),
    path('create', views.create, name="create"),
    path('api/task/create', TaskCreateView.as_view()),
    path('api/task/all', TaskListView.as_view()),
    path('api/task/detail/<int:pk>', TaskDetailView.as_view())
]

taskmanager/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls'))
]

main/models.py
from django.db import models

# Create your models here.
class Task(models.Model):
    title =  models.CharField('Название', max_length=50)
    task = models.TextField('Описание')
    IMPORTANCE_TYPES = (
        (1, 'Высокая'),
        (2, 'Средняя'),
        (3, 'Низкая')
    )
    importance_type = models.IntegerField(verbose_name='Важность', default=2, choices=IMPORTANCE_TYPES)
    date = models.DateTimeField(auto_now_add=True)
    done = models.BooleanField(default=False)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Задача'
        verbose_name_plural = 'Задачи'

main/forms.py
from .models import Task
from django.forms import ModelForm, TextInput, Textarea


class TaskForm(ModelForm):
    class Meta:
        model = Task
        fields = ["title", "task"]
        widgets = {
            "title": TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Введите название'
            }),
            "task": Textarea(attrs={
                'class': 'form-control',
                'placeholder': 'Введите описание'
            })

        }

main/views.py
from django.shortcuts import render, redirect
from .models import Task
from .forms import TaskForm
from rest_framework import generics
from .serializers import TaskDetailSerializer, TaskListSerializer
# Create your views here.

class TaskListView(generics.ListAPIView):
    serializer_class = TaskListSerializer
    queryset = Task.objects.all()

class TaskCreateView(generics.CreateAPIView):
    serializer_class = TaskDetailSerializer

class TaskDetailView(generics.RetrieveUpdateDestroyAPIView):
    serializer_class = TaskDetailSerializer
    queryset = Task.objects.all()


def index(request):
    tasks = Task.objects.all()
    return render(request, 'main/index.html', {'title':'Главная страница сайта', 'tasks': tasks })


def about(request):
    return render(request, 'main/about.html')


def create(request):
    if request.method == 'POST':
        form = TaskForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('home')
        else:
            error = 'Форма неверна'


    form = TaskForm()
    context = {
        'form': form
    }
    return render(request, 'main/create.html', context)

main/templates/main/about.html
{% extends 'main/base.html' %}

{% block title %}
Страница обо мне
{% endblock %}


{% block content %}
    <h3>Страница</h3>
    <p>Обо мне и точка</p>
{% endblock %}

main/templates/main/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>
    <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
      <h5 class="my-0 mr-md-auto font-weight-normal">Company Konstantin</h5>
      <nav class="my-2 my-md-0 mr-md-3">
        <a class= "p-2 text-dark" href="{% url 'home' %}">Features</a>
        <a class="p-2 text-dark" href="{% url 'about' %}">Enterprise</a>
          <a class="p-2 text-dark" href="{% url 'create' %}">Create task</a>

      </nav>
      <a class="btn btn-outline-primary" href="#">Sign up</a>
    </div>
    <div class="container">{% block content %}{% endblock %}</div>
</body>
</html>

main/templates/main/create.html
{% extends 'main/base.html' %}

{% block title %}
Создать таск
{% endblock %}


{% block content %}
    <h3>Создать таск</h3>
    <form method="post">
        {% csrf_token %}
        {{ form.title }}<br>
        {{ form.task }}<br>
        <button type="submit" class="btn btn-success">Добавить</button>
    </form>
{% endblock %}

main/templates/main/index.html
{% extends 'main/base.html' %}

{% block title %}
{{ title }}
{% endblock %}


{% block content %}
    <h3>Главная страница</h3>
    {% for el in tasks %}
        <div class = "alert alert-warning mt-2">
            <h2>{{ el.title }}</h2>
            <p>{{ el.task }}</p><p>{{ el.date }}</p><p>{{ el.done }}</p>
            <div style="position: absolute; right: 20px; bottom: 20px">Важность<p>{{ el.get_importance_type_display }}</p></div>
        </div>
    {% endfor %}
{% endblock %}